export const enum ProposalStatus {
  PROPOSAL_STATUS_UNSPECIFIED = 'PROPOSAL_STATUS_UNSPECIFIED',
  PROPOSAL_STATUS_DEPOSIT_PERIOD = 'PROPOSAL_STATUS_DEPOSIT_PERIOD',
  PROPOSAL_STATUS_VOTING_PERIOD = 'PROPOSAL_STATUS_VOTING_PERIOD',
  PROPOSAL_STATUS_PASSED = 'PROPOSAL_STATUS_PASSED',
  PROPOSAL_STATUS_REJECTED = 'PROPOSAL_STATUS_REJECTED',
  PROPOSAL_STATUS_FAILED = 'PROPOSAL_STATUS_FAILED',
  UNRECOGNIZED = 'UNRECOGNIZED',
}

export const PROPOSAL_STATUS_DISPLAY = {
  PROPOSAL_STATUS_UNSPECIFIED: 'Unspecified',
  PROPOSAL_STATUS_DEPOSIT_PERIOD: 'Depositing Period',
  PROPOSAL_STATUS_VOTING_PERIOD: 'Voting Period',
  PROPOSAL_STATUS_PASSED: 'Passed',
  PROPOSAL_STATUS_REJECTED: 'Rejected',
  PROPOSAL_STATUS_FAILED: 'Failed',
  UNRECOGNIZED: 'Unrecognized',
};
